name: Cyberchat CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: unbuntu-latest
    steps:
      - name: Test code
        run: npm test
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "26"
          cache: "npm"
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "26"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build production
        run: npm run build
